site_name: Documentation for RDAs Toolbox
site_url: https://robotic-discovery-of-antiinfectives.github.io/rda-toolbox/
theme:
  name: material
nav:
  - Overview: index.md
  - Input Specifications: input.md
  - Primary Screen: primary.md
  - MIC: mic.md
  - utility: utility.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/Robotic-Discovery-of-Antiinfectives/rda-toolbox
